name: Feature Request
description: Submit a proposal/request for a new feature.
labels: "enhancement"

body:

  - type: markdown
    attributes:
      value: |
        ## Notice

        1. Please follow the [Code of Conduct](https://github.com/bytedance/bhook/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
        2. Please check [the latest release](https://github.com/bytedance/bhook/releases) to make sure your proposal has not already exists.
        3. Before submitting a feature request, please make sure the proposal hasn't been already addressed by searching through [the existing and past issues](https://github.com/bytedance/bhook/issues?q=is%3Aissue+sort%3Acreated-desc+).

  - type: textarea
    attributes:
      label: the Feature, Motivation and Pitch
      description: >
        A clear and concise description of the feature proposal. Please outline the motivation for the proposal. Is your feature request related to a specific problem? If this is related to another GitHub issue, please link here too.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives
      description: >
        A description of any alternative solutions or features you've considered, if any.

  - type: textarea
    attributes:
      label: Additional context
      description: >
        Add any other context about the feature request.

  - type: markdown
    attributes:
      value: >
        Thanks for contributing! :tada:
